// Code generated by entc, DO NOT EDIT.

package customer

const (
	// Label holds the string label denoting the customer type in the database.
	Label = "customer"
	// FieldID holds the string denoting the id field in the database.
	FieldID           = "customer_id"   // FieldCompanyName holds the string denoting the companyname vertex property in the database.
	FieldCompanyName  = "company_name"  // FieldContactName holds the string denoting the contactname vertex property in the database.
	FieldContactName  = "contact_name"  // FieldContactTitle holds the string denoting the contacttitle vertex property in the database.
	FieldContactTitle = "contact_title" // FieldAddress holds the string denoting the address vertex property in the database.
	FieldAddress      = "address"       // FieldCity holds the string denoting the city vertex property in the database.
	FieldCity         = "city"          // FieldRegion holds the string denoting the region vertex property in the database.
	FieldRegion       = "region"        // FieldPostalCode holds the string denoting the postalcode vertex property in the database.
	FieldPostalCode   = "postal_code"   // FieldCountry holds the string denoting the country vertex property in the database.
	FieldCountry      = "country"       // FieldPhone holds the string denoting the phone vertex property in the database.
	FieldPhone        = "phone"         // FieldFax holds the string denoting the fax vertex property in the database.
	FieldFax          = "fax"

	// Table holds the table name of the customer in the database.
	Table = "customers"
)

// Columns holds all SQL columns for customer fields.
var Columns = []string{
	FieldID,
	FieldCompanyName,
	FieldContactName,
	FieldContactTitle,
	FieldAddress,
	FieldCity,
	FieldRegion,
	FieldPostalCode,
	FieldCountry,
	FieldPhone,
	FieldFax,
}
